/* eslint-disable no-magic-numbers */
/* eslint-env node */

/**
* Configuration object for values shared by multiple components
*/

const Constants = {
  PORT: process.env.PORT || 8000,
  APPDIR: "./app",
  CERTDIR: "./well-known/pki-validation",
  MONGOURL: "mongodb+srv://ur:sketchingwithfriends@sketchingwithfriends.b4fgo.azure.mongodb.net/sketching?retryWrites=true&w=majority",
  SESSION_SECRET: "RufYVOWa7vvyGqldEnWH",
  API_ACCESS_KEY: "2zppbworuyvicyvifj9xswzxoxr6m5jbwh9yv92dyh",
  PASSPORT_SETTINGS: {
    USERNAME_FIELD: "email",
    PASSWORD_FIELD: "password",
  },
  PASSWORD_HASHLENGTH: 10,
  CANVAS_UNDO_STEPS: 5,
  UPLOAD: {
    OPTIONS: {
      ICON: {
        square: true,
        responsive: false,
        greyscale: false,
        quality: 60,
      },
      SKETCH: {
        square: false,
        responsive: false,
        greyscale: false,
        quality: 90,
      },
    },
    AVATAR: {
      FORM_FIELD: "avatar",
      BASE_URL: "/app/resources/img/uploads/avatars",
      STORAGE: "../app/resources/img/uploads/avatars",
      MAX_FILE_SIZE: Math.pow(1024, 3),
    },
    SKETCH: {
      FORM_FIELD: "sketch",
      BASE_URL: "app/resources/img/uploads/sketches/",
      STORAGE: "../app/resources/img/uploads/sketches",
      MAX_FILE_SIZE: Math.pow(1024, 3),
    },
  },
  ROLES: {
    CREATOR: "creator",
    ADMIN: "admins",
    COLLABORATOR: "collaborators",
    VIEWER: "viewers",
  },
  UPLOAD_MAX_SIZE: Math.pow(1024, 3),
  PROFILE_IMAGE_PLACEHOLDER: "/app/resources/img/placeholder.png",
  RESPONSEMESSAGES: {
    UNKNOWN_ROUTE: "Unknown Route",
    UNKNOWN_ERROR: "We're sorry, something went wrong. Please try again later!",
    INVALID_USER_ID: "The provided user id was invalid!",
    INVALID_CHANNEL_ID: "The provided channel id was invalid!",
    LOGIN_FAILED: "Email or Password incorrect!",
    EMAIL_NOT_UNIQUE: "Email already in use!",
    USER_FOUND: "User Lookup Successful!",
    USER_NOT_FOUND: "Could not find User!",
    CHANNEL_FOUND: "Channel Lookup Successful!",
    CHANNEL_NOT_FOUND: "Could not find Channel!",
    CHANNEL_JOIN_SUCCESS: "Successfully joined Channel!",
    CHANNEL_JOIN_ALREADY_MEMBER: "Already a member of this Channel!",
    CHANNEL_JOIN_FAIL: "Could not join Channel!",
    CHANNEL_LEAVE_SUCCESS: "Successfully left Channel!",
    CHANNEL_LEAVE_NOT_MEMBER: "Not a member of this Channel!",
    CHANNEL_LEAVE_FAIL: "Could not leave Channel! Not a Member",
    CHANNEL_LEAVE_IS_CREATOR: "A Channel Creator cannot leave the Channel",
    CHANNEL_KICK_SUCCESS: "Successfully kicked user from Channel!",
    CHANNEL_KICK_NOT_MEMBER: "User is not a member of this Channel!",
    CHANNEL_KICK_FAIL: "Something went wrong trying to kick user from Channel!",
    CREATE_CHANNEL_SUCCESS: "Channel created successfully!",
    CREATE_CHANNEL_FAIL: "Channel could not be created!",
    DELETE_CHANNEL_SUCCESS: "Successfully deleted Channel",
    DELETE_CHANNEL_FAIL: "Only its Creator can delete a Channel",
    CHANNEL_CHANGE_ROLE_SUCCESS: "Successfully changed role for user",
    CHANNEL_CHANGE_ROLE_UNNECESSARY: "User already assigned to this role",
    CHANNEL_CHANGE_ROLE_FAIL: "Failed to assign user to role",
    CHANNEL_ICON_UPLOAD_SUCCESS: "Uploaded icon successfully",
    CHANNEL_ICON_UPLOAD_FAIL: "Failed to upload icon",
    CHANNEL_UPVOTE_FAIL: "Failed to increase score of members for channel",
    SKETCH_NOT_FOUND: "No sketch found!",
    PAGE_NOT_FOUND: "Could not find what you were looking for! :(",
    ADDED_TO_DOWNVOTES: "Added user to downvotes!",
    NOT_ADDED_TO_UPVOTES: "User could not be added to upvotes!",
    NOT_ADDED_TO_DOWNVOTES: "User could not be added to downvotes!",
    ADDED_TO_UPVOTES: "Added user to upvotes!",
    SKETCH_SAVED: "Sketch successfully saved!",
    SKETCH_NOT_SAVED: "Sketch could not be saved!",
    SKETCH_CREATED: "Sketch successfully created!",
    SKETCH_FOUND: "Sketch Lookup Successful!",
    SKETCH_NOT_CREATED: "Could not create new sketch!",
    SKETCH_FINALIZE_FAILED: "Could not finalize and create new Sketch!",
    SKETCH_FINALIZE_SUCCESS: "Sketch successfully finalized and new Sketch was created!",
    SKETCH_PUBLISH_FAILED: "Could not publish Sketch!",
    SKETCH_PUBLISH_SUCCESS: "Sketch successfully published!",
  },
  HTTP_STATUS_CODES: {
    OK: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
  },
  CRYPTO_HEX: 16,
  STATES: {
    ACTIVE: "active",
    INACTIVE: "inactive",
    OFFLINE: "offline",
  },
  SOCKET_KEYS: {
    LINE_DRAW: "line",
    CLEAR_CANVAS: "clear-canvas",
    ADMIN_SETTINGS: "admin-settings",
    TEMPLATE: "template",
    NEW_SKETCH: "new-sketch",
    DELETE_CHANNEL: "delete-channel",
    LINE_UNDO: "undo",
    LINE_HISTORY: "getLineHistory",
    UNSUBSCRIBE: "unsubscribe",
    SUBSCRIBE: "subscribe",
    DISCONNECT: "disconnect",
    CONNECTION: "connection",
    ACTIVE_USERS: "active-users",
  },
};

module.exports = Constants;